### ISSUE TITLE
Rebuild DNLA index

### ISSUE THREAD

**Issue by mikjsmith** [GrahamCobb/humax-unenc-ftp#2]
After a little tinkering, the simplest solution here is to copy the file (using the T2 GUI) to a new directory. This then adds the HD recording to the index.

Any way of achieving the same thing in the perl script?

**Comment by GrahamCobb** [comment]
Thanks for your feedback.

Yes, that is one way and it would be possible to do in the script.  The disadvantages are (i) where to copy it to?, and (ii) you end up with two copies of every file, halving the effective capacity.

In the end I implemented a different solution. If the "--rename" option is given, the script renames the various files for that programme on the disk to add a "-" to the end.  This is enough to trigger getting it added to the index but does **not** cause any visible change in the GUI (the name shown in the GUI comes from the .hmt information not from the filename on the disk).

This works very well -- I use it all the time.  However, there is one small downside: if the programme is actually being watched at the time the rename happens, there is no problem but when you stop watching the system tries to update the .hmt file (to note that the programme has been watched).  This fails and it writes out an invalid .hmt file under the old name and does not update the information in the new file.  This does not cause any serious problem except that the count of programmes in the directory is wrong (so it may say there are two when there is only one, for example) and these bad files get left behind even when you delete the programme.  They are small so it isn't a real problem.

But because of that, I didn't make the --rename option the default.  I also never got around to updating the usage information in the README, which I will do.

**Comment by GrahamCobb** [comment]
It seems I did document the --rename option already.  Despite its small issue I think it is better than copying the file.

**Comment by mikjsmith** [comment]
Ahh - thats perfect!!  Yes, see the rename flag which I'll use from now on. I really was amazed at how easily this works - portable version of perl, run the script and download the HD TS stream. Very effective!
